# Generated by Django 4.2.4 on 2023-08-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_body_en_post_body_ru_post_body_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_uz',
        ),
        migrations.RemoveField(
            model_name='post',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='summary_uz',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_uz',
        ),
    ]
